create database trading_cards_bd;

\c trading_cards_bd

CREATE TABLE public.t_usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome  text NOT NULL,
    email text NOT NULL,
	senha text NOT NULL,
    cpf int8 NOT NULL
);

CREATE TABLE public.t_categoria (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome  text NOT NULL
);

CREATE TABLE public.t_item (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome  text NOT NULL,
    troca bool NOT NULL DEFAULT FALSE,
	venda bool NOT NULL DEFAULT FALSE,
    valor float8 NOT NULL DEFAULT 0,
    ano timestamp DEFAULT NULL,
    numero int8 DEFAULT NULL
);